### ISSUE TITLE
Add `dm_sent` field to infractions database model

### ISSUE THREAD

**Issue by TizzySaurus** [python-discord/api#20]
Refers to [bot#1864](https://github.com/python-discord/bot/issues/1864) and [site#610](https://github.com/python-discord/site/issues/610).

Make the necessary database model changes to [this](https://github.com/python-discord/api/blob/main/api/core/database/models/api/bot/infraction.py) file in order to support infractions having a `dm_sent` field in the database which is shown upon !infraction command.

The field will be a nullable boolean (pre-existing infractions will have the value set to `null`, and future infractions will be set to `true`/`false` accordingly).

**RELEVANT PR TO BE MERGED WITH THOSE OF [bot#1864](https://github.com/python-discord/bot/issues/1864) AND [site#610](https://github.com/python-discord/site/issues/610).**

**Comment by D0rs4n** [comment]
I'll implement this shortly, along with the other change in regarding the Infractions model.

**Comment by TizzySaurus** [comment]
> I'll implement this shortly, along with the other change in regarding the Infractions model.

As discussed on discord, I'm planning to do this myself as part of [bot#1864](https://github.com/python-discord/bot/issues/1864).
